language: python
python: 3.7
script:
- "./test.sh"
- "./build.sh"
deploy:
  provider: pypi
  skip_cleanup: true
  user: blavka
  on:
    tags: true
  password:
    secure: kLTDMRHVpGk20OIFAnnQFqZB9lfxim8PuIxnbn+h3m9d2ngFDEwAO4CEIRu8Lzp3tDpxYFxT+Hzs/yKqwsprho9ptU50PsM4KWMuCvQ2tXCMwULO5gNEETIFFQ1NCqTNn8HrNsjS8/JxgEwrXuGXwiFMXfMV3GM/BTD921hArBBLxP+QQbY7ZgY/qCBbry7KgpXd633r+igy5mo/E3Axec+PcXV5FEoYY5jvgPFaT4UOwWMMAd7xuLUeYb+iDZFcgj/XNN+0IcW5T+4xzsvr5sl4bp+gAHn30LPlR6nVsabas7STXv14MSj1MVDsXeThiVCGFznkdclTECLBKG+Ux0zcDB9i9Dbxo8+4KFPkI2petmI5wdwjRF/bq5BRet+pg/mZnu3RQ42cIlMUbDeFqZxAiFZFLhqU2RSiukDOlCvhey0jt0vPFPD5Wrj46RJTrhU8EPuUDO7/OyWr6dBNUjo4kJ37vGhF3fRAt6aJRb9LzrwqoH4cHXafF8X2UlApYPw8nLx+btWg5BwgkkK0DkSYwM8ZTxKsJD9++kSufkxZEM+DEl+KNqI+hlZ1ZF3hiYEYoKxtyhtgFTvEurdKa3ors/TbOFFwugoiVSxb73jTeY2vkub4LgkcWrT6KfsNK5Uv4oSqzu2bHx+e5aoydYA5DQYZC4C+HXqaR54wDRg=
